name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Environment variables for the job
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoderOne/github-activity-readme@commit-username-and-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # with:
          # COMMIT_MSG: 'Specify a custom commit message'
          # MAX_LINES: 10
